HuskyRescue.Web/Controllers/AdoptionController.cs
using System.Data;
using System.Threading.Tasks;
using HuskyRescue.BusinessLogic;
using HuskyRescue.ViewModel.Adoption;
using HuskyRescue.ViewModel.Common;
using HuskyRescue.Web.Filters;
using Serilog;
using System.Linq;
using System.Web.Mvc;
using System;

namespace HuskyRescue.Web.Controllers
{
    public class AdoptionController : BaseController
    {
        private readonly ILogger _logger;
        private readonly IApplicationManagerService _applicationManagerService;
        private readonly IRescueGroupsManagerService _rescueGroupsManagerService;
        private readonly IBraintreePaymentService _braintreePaymentService;

        public AdoptionController(ILogger iLogger, IApplicationManagerService appservice, IRescueGroupsManagerService iRescueGroupsManagerService, IBraintreePaymentService iBraintreePaymentService)
            : base(iLogger)
        {
            _logger = iLogger;
            _applicationManagerService = appservice;
            _rescueGroupsManagerService = iRescueGroupsManagerService;
            _braintreePaymentService = iBraintreePaymentService;
        }

        [AllowAnonymous]
        public ActionResult Index()
        {
            var huskies = _rescueGroupsManagerService.GetAdoptableHuskiesAsync();

            return View(new RescueGroupAnimals { Animals = huskies });
        }

        [AllowAnonymous]
        [ImportModelStateFromTempData]
        public ActionResult Apply()
        {
            var app = new Apply
                      {
                          AppAddressStateList = ViewModel.Common.Lists.GetStateList(),
                          GenderList = ViewModel.Common.Lists.GetSexTypeList(),
                          ResidenceOwnershipList = ViewModel.Common.Lists.GetResidenceOwnershipTypeList(),
                          ResidencePetDepositCoverageList = ViewModel.Common.Lists.GetResidenceCoverageTypeList(),
                          ResidenceTypeList = ViewModel.Common.Lists.GetResidencTypeList(),
                          StudentTypeList = ViewModel.Common.Lists.GetStudentTypeList(),
                          States = ViewModel.Common.Lists.GetStateList()
                      };

            #region Payment
            // Values needed for submitting a payment to BrainTree
            var token = _braintreePaymentService.GetClientToken(string.Empty);
            ViewData.Add("clientToken", token);
            ViewData.Add("merchantId", AdminSystemSettings.GetSetting("BraintreeMerchantId"));
            ViewData.Add("environment", AdminSystemSettings.GetSetting("BraintreeIsProduction"));
            app.ApplicationFeeAmount = Decimal.Parse(AdminSystemSettings.GetSetting("AdoptionApplicationFee"));
            #endregion

            return View(app);
        }

        [AllowAnonymous]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ExportModelStateToTempData]
        public async Task<ActionResult> Apply(FormCollection formCollection, Apply app)
        {
            // payment information in an encrypted string rather than sending the payment information to the server from the client
            var nonce = formCollection["payment_method_nonce"];
            var deivceData = formCollection["device_data"];

            if (string.IsNullOrEmpty(nonce))
            {
                ModelState.AddModelError("", "incomplete payment information provided");
            }
            else
            {
                // remove comma at end of value
                // comma appears to be a result of two payment_method_nonce fields in the form, one with a value and one without.
                if (nonce.EndsWith(","))
                {
                    nonce = nonce.TrimEnd(',');
                }
                if (nonce.StartsWith(","))
                {
                    nonce = nonce.TrimStart(',');
                }

                try
                {
                    // get model state errors
                    var errors = ModelState.Values.SelectMany(v => v.Errors);
                    
                    // if paying with a credit card the fields for credit card number/cvs/month/year will be invalid because we do not send them to the server
                    // so count the errors on the field validation that do not start with 'card ' (comes from the property attributes in the model class Apply.cs)
                    // TODO validate if this is still needed - all card validation has been removed b/c client side validation requires 'name' properties
                    //      which have been removed for PCI compliance. 
                    var errorCount = errors.Count(m => !m.ErrorMessage.StartsWith("card "));

                    if (errorCount == 0)
                    {
                        app.Nonce = nonce;
                        app.DeviceData = deivceData;

                        var result = await _applicationManagerService.AddAdoptionApplication(app);
                        if (result.Succeeded)
                        {
                            return RedirectToAction("ThankYou");
                        }
                        else
                        {
                            return RedirectToAction("Apply");
                        }
                    }
                    _logger.Information("Adoption App Model Errors {@errors} {@app}", errors, app);
                }
                catch (DataException dex)
                {
                    //Log the error (uncomment dex variable name and add a line here to write a log.
                    ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
                    _logger.Error(dex, "Data Exception saving Adoption Application {@app}", app);
                }
            }
            return RedirectToAction("Apply");
        }

        [AllowAnonymous]
        public ActionResult ThankYou()
        {
            return View();
        }

        [AllowAnonymous]
        public ActionResult Process()
        {
            return View();
        }
    }
}

HuskyRescue.Web/Views/Adoption/Index.cshtml
@model HuskyRescue.ViewModel.Common.RescueGroupAnimals

@section head {
	@Styles.Render("~/Content/css/Adoption-Index")
}

@section scripts{
	<script type="text/javascript">
	var AnimalsObj = JSON.parse(@Html.Raw(Json.Encode(Model.ToJsonString())));
	</script>
	@Scripts.Render("~/bundles/Adoption-Index")
}

<div class="row">
	<div class="large-12 columns text-center">
		<h3>Adoptable Huskies</h3>
	</div>
</div>
<div class="row">
	<div class="large-2 columns text-center">
		<div style="min-width: 150px">
			<img class="center" src="/Content/Images/Huskies/FaceShot_01.jpg" width="250" />
		</div>
	</div>
	<div class="large-8 small-12 columns">
		<div class="page_content content_overflow">
			<p class="strong">Adoption fees are as follows:</p>
			<ul class="nomargin">
				<li>$300<span class="strong">*</span> for adults</li>
				<li>$350<span class="strong">*</span> for puppies under 6 months</li>
			</ul>
			<p><span class="strong">*</span>The fee is an extra $10 (310/360) if paying online.</p>
			<p>
				$100 of each adoption fee is non-refundable if the dog is returned during the trial period.
			</p>
			<p>
				If you are interested in adopting a husky, review our @Html.ActionLink("adoption process", "Process", "Adoption") and then @Html.ActionLink("click here to apply online.", "Apply", "Adoption")
			</p>
		</div>
	</div>
	<div class="large-2 columns text-center">
		<div style="min-width: 150px">
			<img class="center" src="/Content/Images/Huskies/FaceShot_14.jpg" width="250" />
		</div>
	</div>
</div>
<div class="row">
	<div class="large-12 columns" style="background-color: white; padding: 15px">
		@for (var petCounter = 0; petCounter < Model.Count; petCounter++)
		{
			if (petCounter % 8 == 0)
			{
				// start a new row for the first element and before every 9th Animal
			@Html.Raw("<div class='row equalheight'>");
			}

				@Html.Raw("<div class='large-3 medium-6 columns'>");
					@Html.Raw("<div class='row'>");
						@Html.Raw("<div class='large-6 small-6 columns heightset'>");
							if (petCounter < Model.Animals.Count)
							{
								Html.RenderPartial("_RescueGroupAnimal", Model.Animals[petCounter]);
								petCounter++;
							}
							else { petCounter++;}
						@Html.Raw("</div>");
						@Html.Raw("<div class='large-6 small-6 columns heightset'>");
							if (petCounter < Model.Animals.Count)
							{
								Html.RenderPartial("_RescueGroupAnimal", Model.Animals[petCounter]);
							}
						@Html.Raw("</div>");
					@Html.Raw("</div>");
				@Html.Raw("</div>");

			if ((petCounter + 1) % 8 == 0)
			{
				// close row div after 8th Animal
			@Html.Raw("</div>");
			}
		}
	</div>
</div>
<div id="AnimalDetailModal" class="reveal-modal medium" data-reveal>
	<a class="close-reveal-modal">&#215;</a>
	<div class="row">
		<div class="large-12 columns">
			<h2 id="petName"></h2>
			<hr />
			<h6 class="subheader" id="petSexAge" style="text-align: center"></h6>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<div id="petPictures">
			</div>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<div id="petBio"></div>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<div id="petAttributes"></div>
		</div>
	</div>
	<div class="row">
		<div class="large-12 columns">
			<a class="tiny button" id="revealClose">Close</a>
		</div>
	</div>
</div>

HuskyRescue.Web/Views/Adoption/Process.cshtml
<div class="row">
	<div class="large-12 columns text-center">
		<h3>Adoption Process</h3>
	</div>
</div>
<div class="row">
	<div class="large-2 columns text-center">
		<div>
			<img src="/Content/Images/Huskies/FaceShot_10.jpg" height="250" />
		</div>
	</div>
	<div class="large-8 columns">
		<div>
			<p>
				The adoption process has several stages to ensure our huskies are going to qualified, educated, loving forever homes.
			</p>
			<p>
				All TXHR huskies are spayed or neutered, current on vaccinations, taking heartworm prevention, and are microchipped prior to adoption.
			</p>
			<p>
				Adoption fees<strong>*</strong> are $300 for adult males and females; $350 for puppies under 6 months.
				<br />
				<strong>NOTE</strong>: $100 is non-refundable if the husky is returned during the trial period.
			</p>
			<p><strong>*</strong>The fee is an extra $10 (310/360) if paying by PayPal.</p>
			<p>
				<a href="https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&amp;hosted_button_id=RNTPPJFU4E666" target="_blank">Pay your adoption fee here </a>
			</p>
		</div>
	</div>
	<div class="large-2 columns text-center">
		<div>
			<img src="/Content/Images/Huskies/FaceShot_36.jpg" height="250" />
		</div>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<div>
			<ul>
				<li>
					@Html.ActionLink("Apply Online", "Apply", "Adoption") or complete a <a href="/Forms/adoptionapplication.pdf">PDF adoption application</a>. The PDF application
					@Html.ActionLink("can be emailed", "Contact", "Home"), faxed to 1-877-894-8759, or mailed to PO Box 118891, Carrollton, TX 75011.
				</li>
				<li>
					Once your application is received, we will conduct a thorough screening process which includes a vet check of your current pets and a phone screen/interview
					by one of our adoption coordinators.
				</li>
				<li>
					After your vet check and phone screen are completed successfully, TXHR will conduct a fence/home check. This is a check for gaps, broken slats, holes,
					compromised spots, etc where a husky could escape. Please do a walk of the perimeter of your fence and fix all problem spots before we come to your home.
				</li>
				<li>
					Upon successful completion of the application process, a TXHR adoption counselor will set up a meet and greet with you and the husky you have applied
					for. Once you determine you would like to adopt the husky, you must sign an adoption contract and pay the adoption fee before taking possession of the
					husky.
				</li>
				<li>All adoptions start with a 5 day trial period to ensure the husky is a good fit in your home and lifestyle.</li>+
			</ul>
			<br />
			<p>
				Download the <a href="/Forms/adoption-contract.pdf">Adoption Contract</a>
			</p>
		</div>
	</div>
</div>

HuskyRescue.Web/Views/Adoption/ThankYou.cshtml
<div class="row">
	<div class="large-12 columns">
		<h2>
			Thank you for applying to adopt one (or more) of our wonderful huskies!
		</h2>
	</div>
</div>
<div class="row">
	<div class="large-12 columns">
		<p>You will receive a copy of your application via email shortly.</p>
		<hr/>
		<h4>What's next?</h4>
		<p>Once your application is received, we will conduct a thorough screening process which includes a vet check of your current pets.</p>
		<p>
			After you have been initially approved and your vet check is completed successfully, TXHR will conduct a fence/home check. This is a check for gaps, broken
			slats, holes, compromised spots, etc where a husky could escape from. Please do a walk of the perimeter of your fence and fix all problem spots before
			we come to your home.
		</p>
		<p>
			Upon successful completion of the application process, a TXHR adoption counselor will set up a meet and greet with you and the husky you have applied
			for. Once you determine you would like to adopt the husky, you must sign an adoption contract and pay the adoption fee before taking possession of the
			husky.
		</p>
		<p>All adoptions start with a 5 day trial period to ensure the husky is a good fit in your home and lifestyle.</p>
		<hr/>
		<p>
			If you have questions or concerns during the process please @Html.ActionLink("contact us", "Contact", "Home").
		</p>
	</div>
</div>

HuskyRescue.Web/Views/Adoption/_RescueGroupAnimal.cshtml
@using HuskyRescue.Web.HtmlHelpers
@model HuskyRescue.ViewModel.Common.RescueGroupAnimal
<div class="AnimalCell" id="@Model.AnimalId">
	<table>
		<tbody>
			<tr>
				<td class="AnimalThumbPix">
					@if (Model.AnimalPictures != null)
					{
						if (Model.AnimalPictures.Count > 0)
						{
							if (!string.IsNullOrEmpty(Model.AnimalPictures[0].UrlSecureThumbnail))
							{
								@Html.Image(Model.AnimalPictures[0].UrlSecureThumbnail, Model.AnimalName, new { width = "100" })
							}
						}
					}
				</td>
			</tr>
		</tbody>
	</table>
	<div class="petinfo">
		<div class="petSummaryText petName">@Html.DisplayTextFor(model => model.AnimalName)</div>
		<div class="petSummaryText">@Html.DisplayTextFor(model => model.AnimalBreed)</div>
	</div>
</div>