HuskyRescue.Web/Controllers/AdminEventsController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using HuskyRescue.BusinessLogic;
using HuskyRescue.ViewModel.Events;
using HuskyRescue.Web.Filters;
using Microsoft.AspNet.Identity;
using Serilog;

namespace HuskyRescue.Web.Controllers
{
	public class AdminEventsController : BaseController
	{
		private readonly ILogger _logger;
		private readonly IAdminEventsManagerService _adminEventsManagerService;
		private readonly IAdminOrganizationsManagerService _adminOrganizationsManagerService;
		

		public AdminEventsController(ILogger iLogger, IAdminEventsManagerService iAdminEventsManagerService,
			IAdminOrganizationsManagerService iAdminOrganizationsManagerService): base(iLogger)
		{
			_logger = iLogger;
			_adminEventsManagerService = iAdminEventsManagerService;
			_adminOrganizationsManagerService = iAdminOrganizationsManagerService;
		}

		public async Task<ActionResult> Index()
		{
			var events = await _adminEventsManagerService.GetAllEventsListAsync();
			return View(events);
		}

		[ImportModelStateFromTempData]
		public async Task<ActionResult> Create()
		{
			var eventObj = new Create();

			var organizations = await _adminOrganizationsManagerService.GetFilteredOrgsListAsync();

			foreach (var org in organizations)
			{
				eventObj.Organizations.Add(new SelectListItem
				                           {
					                           Text = org.Name,
											   Value = org.Id.ToString()
				                           });
			}

			return View(eventObj);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public async Task<ActionResult> Create(Create eventObj, FormCollection form)
		{
			try
			{
				// get model state errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);

				if (!errors.Any())
				{
					eventObj.AddedByUserId = User.Identity.GetUserId();

					var result = await _adminEventsManagerService.AddEventAsync(eventObj);
					if (result.Succeeded)
					{
						return RedirectToAction("Index");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}
					return RedirectToAction("Create");
				}
			}
			catch (Exception ex)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to process creation of new event. Try again, and if the problem persists contact the admin (James).");

				_logger.Error(ex, "Event add error: {message} {@ex}", ex.Message, ex);
			}
			return RedirectToAction("Create");
		}

		[ImportModelStateFromTempData]
		public async Task<ActionResult> Edit(Guid id)
		{
			var eventObj = await _adminEventsManagerService.GetEventByIdAsync(id);

			var organizations = await _adminOrganizationsManagerService.GetFilteredOrgsListAsync();

			foreach (var org in organizations)
			{
				eventObj.Organizations.Add(new SelectListItem
				{
					Text = org.Name,
					Value = org.Id.ToString()
				});
			}

			return View(eventObj);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public async Task<ActionResult> Edit(Edit eventObj, FormCollection form)
		{
			try
			{
				// get model state errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);

				if (!errors.Any())
				{
					eventObj.UpdatedByUserId = User.Identity.GetUserId();

					var result = await _adminEventsManagerService.EditEventAsync(eventObj);
					if (result.Succeeded)
					{
						return RedirectToAction("Index");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}
					return RedirectToAction("Edit");
				}
			}
			catch (Exception ex)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to process update of event. Try again, and if the problem persists contact the admin (James).");

				_logger.Error(ex, "Event add error: {message} {@ex}", ex.Message, ex);
			}
			return RedirectToAction("Edit");
		}
	}
}

HuskyRescue.Web/Controllers/AdminEventsSponsorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HuskyRescue.BusinessLogic;
using HuskyRescue.ViewModel.EventsSponsor;
using HuskyRescue.Web.Filters;
using Microsoft.AspNet.Identity;
using Serilog;
using System.IO;

namespace HuskyRescue.Web.Controllers
{
	public class AdminEventsSponsorsController : BaseController
	{
		private readonly ILogger _logger;
		private readonly IAdminEventsManagerService _adminEventsManagerService;

		private readonly IAdminEventsSponsorManagerService _adminEventsSponsorManagerService;

		private readonly IAdminEventsSponsorshipManagerService _adminEventsSponsorshipManagerService;

		private readonly IAdminOrganizationsManagerService _adminOrganizationsManagerService;

		public AdminEventsSponsorsController(ILogger iLogger, IAdminEventsManagerService iAdminEventsManagerService,
			IAdminEventsSponsorManagerService iAdminEventsSponsorManagerService,
			IAdminOrganizationsManagerService iAdminOrganizationsManagerService,
			IAdminEventsSponsorshipManagerService iAdminEventsSponsorshipManagerService)
			: base(iLogger)
		{
			_logger = iLogger;
			_adminEventsManagerService = iAdminEventsManagerService;
			_adminEventsSponsorManagerService = iAdminEventsSponsorManagerService;
			_adminOrganizationsManagerService = iAdminOrganizationsManagerService;
			_adminEventsSponsorshipManagerService = iAdminEventsSponsorshipManagerService;
		}

		public async Task<ActionResult> Index()
		{
			var sponsors = await _adminEventsSponsorManagerService.GetAllSponsorsListAsync();
			return View(sponsors);
		}

		[ImportModelStateFromTempData]
		public async Task<ActionResult> Create()
		{
			var sponsor = new Create();

			var events = await _adminEventsManagerService.GetAllEventsListAsync();

			sponsor.Events.Add(new SelectListItem
			{
				Text = "-- event name --",
				Value = string.Empty,
				Selected = true
			});

			foreach (var eventItem in events)
			{
				sponsor.Events.Add(new SelectListItem
								   {
									   Text = eventItem.EventName,
									   Value = eventItem.Id.ToString()
								   });
			}

			var organizations = await _adminOrganizationsManagerService.GetFilteredOrgsListAsync();

			sponsor.Organizations.Add(new SelectListItem
									{
										Text = "-- sponsor name --",
										Value = string.Empty,
										Selected = true
									});

			foreach (var org in organizations)
			{
				sponsor.Organizations.Add(new SelectListItem
										   {
											   Text = org.Name,
											   Value = org.Id.ToString()
										   });
			}

			foreach (var org in organizations)
			{
				sponsor.Organizations.Add(new SelectListItem
				{
					Text = org.Name,
					Value = org.Id.ToString()
				});
			}

			sponsor.People.Add(new SelectListItem { Disabled = true, Text = "No People", Value = "" });

			//var sponsorships = await _adminEventsSponsorshipManagerService.GetAllSponsorshipsListAsync();

			//foreach (var s in sponsorships)
			//{
			//	sponsor.EventSponsorships.Add(new SelectListItem
			//								   {
			//									   Text = s.Name,
			//									   Value = s.Id.ToString()
			//								   });
			//}

			return View(sponsor);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public async Task<ActionResult> Create(Create sponsorObj, FormCollection form)
		{
			const string virtualDirectory = @"\Content\Images\Controllers\Golf\";

			try
			{
				// get model state errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);

				if (!errors.Any())
				{
					HttpPostedFileBase postedFile = null;
					foreach (var fileObject in Request.Files)
					{
						postedFile = Request.Files[(string)fileObject];
						//Save file content goes here
						if (postedFile == null || postedFile.ContentLength <= 0) continue;
						//var physicalDirectory = Server.MapPath(virtualDirectory);

						//var fileName = postedFile.FileName;

						//var fileInfo = new FileInfo(Path.Combine(physicalDirectory, fileName));

						//if (fileInfo.Exists)
						//{
						//	fileName = fileInfo.Name.Insert(fileInfo.Name.Length - (fileInfo.Extension.Length), "-" + DateTime.Now);
						//}

						//var path = string.Format("{0}\\{1}", fileInfo.Directory.FullName, fileName);
						//sponsorObj.LogoFilePhysicalPath = path;
						sponsorObj.LogoFileName = postedFile.FileName;
						sponsorObj.FileLogoContentType = postedFile.ContentType;

						using (var reader = new BinaryReader(postedFile.InputStream))
						{
							sponsorObj.FileLogoContent = reader.ReadBytes(postedFile.ContentLength);
						}
					}

					sponsorObj.AddedByUserId = User.Identity.GetUserId();

					var result = await _adminEventsSponsorManagerService.AddEventSponsorAsync(sponsorObj);
					if (result.Succeeded)
					{
						if (postedFile != null)
						{
							postedFile.SaveAs(sponsorObj.LogoFilePhysicalPath);
						}

						return RedirectToAction("Index");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}
					return RedirectToAction("Create");
				}

			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", "Unable to process creation of new event sponsor. Try again, and if the problem persists contact the admin (James).");

				_logger.Error(ex, "Sponsor add error: {message} {@ex}", ex.Message, ex);
			}

			return RedirectToAction("Index");
		}

		[ImportModelStateFromTempData]
		public ActionResult Edit()
		{
			return View();
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public ActionResult Edit(FormCollection form)
		{
			return View();
		}
	}
}

HuskyRescue.Web/Controllers/AdminEventsSponsorshipController.cs
using HuskyRescue.BusinessLogic;
using HuskyRescue.ViewModel.EventsSponsorship;
using HuskyRescue.Web.Filters;
using Microsoft.AspNet.Identity;
using Serilog;
using System;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace HuskyRescue.Web.Controllers
{
	public class AdminEventsSponsorshipController : BaseController
	{
		private readonly ILogger _logger;
		private readonly IAdminEventsManagerService _adminEventsManagerService;
		private readonly IAdminEventsSponsorshipManagerService _adminEventsSponsorshipManagerService;
		private readonly IAdminOrganizationsManagerService _adminOrganizationsManagerService;

		public AdminEventsSponsorshipController(ILogger iLogger, IAdminEventsManagerService iAdminEventsManagerService,
			IAdminEventsSponsorshipManagerService iAdminEventsSponsorshipManagerService,
			IAdminOrganizationsManagerService iAdminOrganizationsManagerService)
			: base(iLogger)
		{
			_logger = iLogger;
			_adminEventsManagerService = iAdminEventsManagerService;
			_adminEventsSponsorshipManagerService = iAdminEventsSponsorshipManagerService;
			_adminOrganizationsManagerService = iAdminOrganizationsManagerService;
		}

		// GET: AdminEventsSponsorship
		public async Task<ActionResult> Index()
		{
			var eventSponsorships = await _adminEventsSponsorshipManagerService.GetAllSponsorshipsListAsync();
			return View(eventSponsorships);
		}

		[HttpPost]
		public async Task<JsonResult> ListByEvent(Guid eventId)
		{
			var eventSponsorships = await _adminEventsSponsorshipManagerService.GetEventSponsorshipsListAsync(eventId);
			return Json(eventSponsorships);
		}

		[ImportModelStateFromTempData]
		public async Task<ActionResult> Create()
		{
			var sponsorship = new Create();

			var events = await _adminEventsManagerService.GetAllEventsListAsync();

			foreach (var e in events)
			{
				sponsorship.Events.Add(new SelectListItem
										   {
											   Text = e.EventName,
											   Value = e.Id.ToString()
										   });
			}

			return View(sponsorship);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public async Task<ActionResult> Create(Create sponsorshipObj, FormCollection form)
		{
			try
			{
				// get model state errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);

				if (!errors.Any())
				{
					sponsorshipObj.AddedByUserId = User.Identity.GetUserId();

					var result = await _adminEventsSponsorshipManagerService.AddEventSponsorshipAsync(sponsorshipObj);
					if (result.Succeeded)
					{
						return RedirectToAction("Index");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}
					return RedirectToAction("Create");
				}
			}
			catch (Exception ex)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to process creation of new event sponsorship. Try again, and if the problem persists contact the admin (James).");

				_logger.Error(ex, "Sponsorship add error: {message} {@ex}", ex.Message, ex);
			}
			return RedirectToAction("Create");
		}

		[ImportModelStateFromTempData]
		public async Task<ActionResult> Edit(string id)
		{
			if (string.IsNullOrEmpty(id)) RedirectToAction("Index");

			var eventId = new Guid(id);

			var sponsorship = _adminEventsSponsorshipManagerService.GetSponsorshipDetailForEdit(eventId);
			
			var events = await _adminEventsManagerService.GetAllEventsListAsync();

			foreach (var e in events)
			{
				sponsorship.Events.Add(new SelectListItem
										   {
											   Text = e.EventName,
											   Value = e.Id.ToString(),
											   Selected = e.Id.Equals(eventId)
										   });
			}

			return View(sponsorship);
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		[ExportModelStateToTempData]
		public async Task<ActionResult> Edit(Edit sponsorshipObj, FormCollection form)
		{
			try
			{
				// get model state errors
				var errors = ModelState.Values.SelectMany(v => v.Errors);

				if (!errors.Any())
				{
					sponsorshipObj.UpdatedByUserId = User.Identity.GetUserId();

					var result = await _adminEventsSponsorshipManagerService.UpdateEventSponsorshipAsync(sponsorshipObj);
					if (result.Succeeded)
					{
						return RedirectToAction("Index");
					}
					foreach (var error in result.Errors)
					{
						ModelState.AddModelError("", error);
					}
					return RedirectToAction("Edit");
				}
			}
			catch (Exception ex)
			{
				//Log the error (uncomment ex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to process update of existing event sponsorship. Try again, and if the problem persists contact the admin (James).");

				_logger.Error(ex, "Sponsorship update error: {message} {@ex}", ex.Message, ex);
			}
			return RedirectToAction("Edit");
		}
	}
}

HuskyRescue.Web/Views/AdminEventsSponsors/Create.cshtml
@using HuskyRescue.Web.HtmlHelpers
@model HuskyRescue.ViewModel.EventsSponsor.Create

@section scripts
{
	@Scripts.Render("~/bundles/AdminEventsSponsors-Create")
}

@section head {
}

<div class="row">
	<div class="large-12 columns">
		@using (Html.BeginForm("Create", "AdminEventsSponsors", FormMethod.Post, new { id = "adminEventsSponsorsForm", enctype = "multipart/form-data" }))
		{
			@Html.AntiForgeryToken()
			@Html.ValidationSummary(true)

			<div class="row">
				<div class="large-6 small-12 small-centered large-centered columns"><h2>Add New Sponsor</h2></div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					@Html.LabelDropDownFor(m => m.EventId, Model.Events)
					@Html.ValidationMessageFor(m => m.EventId)
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					@Html.LabelDropDownFor(m => m.EventSponsorshipId, Model.EventSponsorships)
					@Html.ValidationMessageFor(m => m.EventSponsorshipId)
				</div>
			</div>
			<div class="row">
				<div class="large-6 columns">
					<div class="row">
						<div class="large-4 columns">
							@Html.LabelCheckboxFor(m => m.HasPaid)
						</div>
						<div class="large-4 columns end">
							@Html.LabelTextBoxFor(m => m.AmountPaid)
							@Html.ValidationMessageFor(m => m.AmountPaid)
						</div>
					</div>
					<div class="row">
						<div class="large-4 columns">
							@Html.LabelCheckboxFor(m => m.HaveReceivedLogo)
						</div>
						<div class="large-4 columns end">
							@Html.LabelCheckboxFor(m => m.HaveReceivedSingage)
						</div>
					</div>
					<br/>
					<div class="row">
						<div class="large-6 medium-12 small-12 end columns">
							@Html.TextBoxFor(m => m.FileLogoName, new { type = "file" })
							@Html.ValidationMessageFor(m => m.FileLogoName)
						</div>
					</div>
				</div>
				<div class="large-6 columns">
					@Html.LabelTextAreaFor(m => m.InternalNotes)
					@Html.ValidationMessageFor(m => m.InternalNotes)
				</div>
			</div>
			<br/>
			<div class="row">
				<div class="large-12 columns">
					@Html.LabelRadioButtonFor(m => m.SponsorType, new List<KeyValuePair<string, object>> { new KeyValuePair<string, object>("Person", "P"), new KeyValuePair<string, object>("Business", "B") })
					@Html.ValidationMessageFor(m => m.SponsorType)
					@Html.HiddenFor(m => m.IsBusinessSponsor)
					@Html.HiddenFor(m => m.IsPersonSponsor)
				</div>
			</div>
			<div id="businessFields">
				<div class="row">
					<div class="large-12 columns">
						@Html.LabelRadioButtonFor(m => m.IsNewOrg, new List<KeyValuePair<string, object>> { new KeyValuePair<string, object>("New", "true"), new KeyValuePair<string, object>("Existing", "false") })
					</div>
				</div>
				<div id="RowOrgExisting">
					<div class="row">
						<div class="large-12 columns">
							@Html.LabelDropDownFor(m => m.OrganizationId, Model.Organizations)
							@Html.ValidationMessageFor(m => m.OrganizationId)
						</div>
					</div>
				</div>
				<div id="RowOrgNew">
					<div class="row">
						<div class="large-12 columns">
							<h4>New Business Information</h4>
						</div>
					</div>
					<div class="row">
						<div class="large-12 columns">
							@Html.LabelTextBoxFor(m => m.OrgName)
						</div>
					</div>
				</div>
			</div>
			<div id="personFields">
				<div class="row">
					<div class="large-12 columns">
						@Html.LabelRadioButtonFor(m => m.IsNewPerson, new List<KeyValuePair<string, object>> { new KeyValuePair<string, object>("New", "true"), new KeyValuePair<string, object>("Existing", "false") })
					</div>
				</div>
				<div id="RowPersonExisting">
					<div class="row">
						<div class="large-12 columns">
							@Html.LabelDropDownFor(m => m.PeopleId, Model.People)
							@Html.ValidationMessageFor(m => m.PeopleId)
						</div>
					</div>
				</div>
				<div id="RowPersonNew">
					<div class="row">
						<div class="large-12 columns">
							<h4>New Person Information</h4>
						</div>
					</div>
					<div class="row">
						<div class="large-6 columns">
							@Html.LabelTextBoxFor(m => m.FirstName)
						</div>
						<div class="large-6 columns">
							@Html.LabelTextBoxFor(m => m.LastName)
						</div>
					</div>
				</div>
			</div>
			<div id="RowNewEntity">
				<div class="row">
					<div class="large-12 columns">
						<h5>Contact Information</h5>
					</div>
				</div>
				<div class="row">
					<div class="large-1 columns">
						@Html.LabelDropDownFor(m => m.PhoneNumber1TypeId, Model.PhoneNumberTypes)
						@Html.ValidationMessageFor(m => m.PhoneNumber1TypeId)
					</div>
					<div class="large-2 columns">
						@Html.LabelTextBoxFor(m => m.PhoneNumber1)
						@Html.ValidationMessageFor(m => m.PhoneNumber1)
					</div>
					<div class="large-1 columns">
						@Html.LabelDropDownFor(m => m.PhoneNumber2TypeId, Model.PhoneNumberTypes)
						@Html.ValidationMessageFor(m => m.PhoneNumber2TypeId)
					</div>
					<div class="large-2 columns">
						@Html.LabelTextBoxFor(m => m.PhoneNumber2)
						@Html.ValidationMessageFor(m => m.PhoneNumber2)
					</div>
					<div class="large-1 columns">
						@Html.LabelDropDownFor(m => m.PhoneNumber3TypeId, Model.PhoneNumberTypes)
						@Html.ValidationMessageFor(m => m.PhoneNumber3TypeId)
					</div>
					<div class="large-2 end columns">
						@Html.LabelTextBoxFor(m => m.PhoneNumber3)
						@Html.ValidationMessageFor(m => m.PhoneNumber3)
					</div>
				</div>
				<div class="row">
					<div class="large-1 columns">
						@Html.LabelDropDownFor(m => m.Email1TypeId, Model.EmailTypes)
						@Html.ValidationMessageFor(m => m.Email1TypeId)
					</div>
					<div class="large-5 columns">
						@Html.LabelTextBoxFor(m => m.Email1)
						@Html.ValidationMessageFor(m => m.Email1)
					</div>
					<div class="large-1 columns">
						@Html.LabelDropDownFor(m => m.Email2TypeId, Model.EmailTypes)
						@Html.ValidationMessageFor(m => m.Email2TypeId)
					</div>
					<div class="large-5 columns">
						@Html.LabelTextBoxFor(m => m.Email2)
						@Html.ValidationMessageFor(m => m.Email2)
					</div>
				</div>
				<div class="row">
					<div class="large-12 columns">
						@Html.LabelTextBoxFor(m => m.Website)
						@Html.ValidationMessageFor(m => m.Website)
					</div>
				</div>
				<div class="row">
					<div class="large-12 columns">
						<h5>Physical Address</h5>
					</div>
				</div>
				<div class="row">
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.PhysicalAddressStreet1)
						@Html.ValidationMessageFor(m => m.PhysicalAddressStreet1)
					</div>
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.PhysicalAddressStreet2)
						@Html.ValidationMessageFor(m => m.PhysicalAddressStreet2)
					</div>
				</div>
				<div class="row">
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.PhysicalAddressCity)
						@Html.ValidationMessageFor(m => m.PhysicalAddressCity)
					</div>
					<div class="large-2 columns">
						@Html.LabelDropDownFor(m => m.PhysicalAddressStateId, Model.AddressStates)
						@Html.ValidationMessageFor(m => m.PhysicalAddressStateId)
					</div>
					<div class="large-1 columns end">
						@Html.LabelTextBoxFor(m => m.PhysicalAddressPostalCode, null, new { placeholder = "12345" })
						@Html.ValidationMessageFor(m => m.PhysicalAddressPostalCode)
					</div>
				</div>

				<div class="row">
					<div class="large-12 columns">
						<h5>Mailing Address</h5>
					</div>
				</div>
				<div class="row">
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.MailingAddressStreet1)
						@Html.ValidationMessageFor(m => m.MailingAddressStreet1)
					</div>
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.MailingAddressStreet2)
						@Html.ValidationMessageFor(m => m.MailingAddressStreet2)
					</div>
				</div>
				<div class="row">
					<div class="large-6 columns">
						@Html.LabelTextBoxFor(m => m.MailingAddressCity)
						@Html.ValidationMessageFor(m => m.MailingAddressCity)
					</div>
					<div class="large-2 columns">
						@Html.LabelDropDownFor(m => m.MailingAddressStateId, Model.AddressStates)
						@Html.ValidationMessageFor(m => m.MailingAddressStateId)
					</div>
					<div class="large-1 columns end">
						@Html.LabelTextBoxFor(m => m.MailingAddressPostalCode, null, new { placeholder = "12345" })
						@Html.ValidationMessageFor(m => m.MailingAddressPostalCode)
					</div>
				</div>
			</div>


			<div class="row">
				<div class="large-12 columns">
					<input type="submit" value="Create" class="button small success" />
				</div>
			</div>
		}

		<div>
			@Html.ActionLink("Back to List", "Index")
		</div>
	</div>
</div>

HuskyRescue.Web/Views/AdminEventsSponsors/Index.cshtml
@model IEnumerable<HuskyRescue.ViewModel.EventsSponsor.List>

<div class="row">
	<div class="large-6 small-12 small-centered large-centered columns"><h2>All Event Sponsorships</h2></div>
</div>
<div class="row">
	<div class="large-12 columns">

		<p>
			@Html.ActionLink("Create New", "Create")
		</p>
		<table class="table">
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.SponsorName)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.EventName)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.HaveReceivedLogo)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.HaveReceivedSingage)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.HasPaid)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.AmountPaid)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.AddedByUserId)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.UpdatedByUserId)
				</th>
				<th></th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.ActionLink(item.SponsorName, "Edit", item.IsPerson ? "AdminPeople" : "AdminOrganizations", new { @id = item.OrgPersonId })
					</td>
					<td>
						@Html.ActionLink(item.EventName, "Edit", "AdminEvents", new { @id = item.EventId })
					</td>
					<td>
						@Html.ActionLink(item.EventName, "Edit", "AdminEventsSponsorship", new { @id = item.EventSponsoshipId })
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.HaveReceivedLogo)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.HaveReceivedSingage)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.HasPaid)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.AmountPaid)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.AddedByUserId)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.UpdatedByUserId)
					</td>
					<td>
						@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
						@Html.ActionLink("Details", "Details", new { id = item.Id }) |
						@Html.ActionLink("Delete", "Delete", new { id = item.Id })
					</td>
				</tr>
			}

		</table>
	</div>
</div>