HuskyRescue.Web/Controllers/AdminIdentityResourcesController.cs
using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using System.Web.Mvc;
using HuskyRescue.BusinessLogic.Identity;
using HuskyRescue.ViewModel.Admin.ResourceManager;
using HuskyRescue.Web.Filters;
using Serilog;

namespace HuskyRescue.Web.Controllers
{
	[AllowAnonymous]
	public class AdminIdentityResourcesController : BaseController
	{
		private readonly ILogger _logger;

		public IResourceManagerService ResourceManagerService { get; set; }

		public AdminIdentityResourcesController(ILogger iLogger, IResourceManagerService resourceManagerService) : base(iLogger)
		{
			_logger = iLogger;
			ResourceManagerService = resourceManagerService;
		}

		// GET: ResourceManager
		public async Task<ActionResult> Index()
		{
			var resources = await ResourceManagerService.GetResourceListAsync();
			var resourceCompare = new ResourceIndexCompare();
			resources.Sort(resourceCompare);
			return View(resources);
		}

		// GET: ResourceManager/Details/5
		public async Task<ActionResult> Details(string id)
		{
			var resource = await ResourceManagerService.GetResourceDetailAsync(id);
			return View(resource);
		}

		// GET: ResourceManager/Create
		[ImportModelStateFromTempData]
		public ActionResult Create()
		{
			return View(new ResourceCreate());
		}

		// POST: ResourceManager/Create
		[HttpPost, ValidateAntiForgeryToken, ExportModelStateToTempData]
		public async Task<ActionResult> Create(ResourceCreate resourceCreate)
		{
			try
			{
				if (ModelState.IsValid)
				{
					var result = await ResourceManagerService.AddResourceAsync(resourceCreate);
					if (result.Succeeded)
					{
						return RedirectToAction("Index");
					}
					else
					{
						return RedirectToAction("Create");
					}
				}
			}
			catch (DataException /* dex */)
			{
				//Log the error (uncomment dex variable name and add a line here to write a log.
				ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
			}
			return RedirectToAction("Create");
		}

		// GET: ResourceManager/Edit/5
		public ActionResult Edit(int id)
		{
			return View();
		}

		// POST: ResourceManager/Edit/5
		[HttpPost]
		public ActionResult Edit(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add update logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}

		// GET: ResourceManager/Delete/5
		public ActionResult Delete(int id)
		{
			return View();
		}

		// POST: ResourceManager/Delete/5
		[HttpPost]
		public ActionResult Delete(int id, FormCollection collection)
		{
			try
			{
				// TODO: Add delete logic here

				return RedirectToAction("Index");
			}
			catch
			{
				return View();
			}
		}
	}
}

HuskyRescue.Web/Views/AdminIdentityResources/Create.cshtml
@using HuskyRescue.Web.HtmlHelpers
@model HuskyRescue.ViewModel.Admin.ResourceManager.ResourceCreate

@{
	ViewBag.Title = "Create";
}

@section scripts
{
	<script>
		//$("form").validate();
	</script>
}

<div class="row">
	<div class="large-12 columns">

		@using (Html.BeginForm("Create", "AdminIdentityResources", FormMethod.Post, new { id = "resourceCreate" }))
		{
			@Html.AntiForgeryToken()
			@Html.ValidationSummary(true)
			<div class="row">
				<div class="large-6 small-12 small-centered large-centered columns"><h2>Create New Resource</h2></div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.ValidationSummary(true, "", new { @class = "text-danger" })</div>
			</div>

			<div class="row">
				<div class="large-12 columns">
					@Html.LabelTextBoxFor(m => m.Controller)
					@Html.ValidationMessageFor(m => m.Controller)

				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelTextBoxFor(m => m.ControllerAction) @Html.ValidationMessageFor(m => m.ControllerAction)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelDropDownFor(m => m.Action, Model.Actions) @Html.ValidationMessageFor(m => m.Action)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelCheckboxFor(m => m.IsCreate)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelCheckboxFor(m => m.IsDelete)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelCheckboxFor(m => m.IsExecute)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelCheckboxFor(m => m.IsRead)</div>
			</div>
			<div class="row">
				<div class="large-12 columns">@Html.LabelCheckboxFor(m => m.IsUpdate)</div>
			</div>
			<div class="row">
				<div class="large-12 columns large-centered small-centered">
					<input type="submit" value="Create" class="button small success" />
					@*<a role="button"></a>*@
					@Html.ActionLink("Cancel", "Index", "AdminIdentityResources", new { @role = "button", @class = "button alert small" })

				</div>
			</div>
		}
	</div>
</div>

HuskyRescue.Web/Views/AdminIdentityResources/Details.cshtml
@model HuskyRescue.ViewModel.Admin.ResourceManager.ResourceDetail

<div class="row">
	<div class="large-12 columns">
		
		<div class="row">
			<div class="large-6 small-12 small-centered large-centered columns"><h2>Resource Details</h2></div>
		</div>

		<div class="row">
			<div class="large-2 columns">@Html.LabelFor(m => m.Name)</div>
			<div class="large-10 columns">@Html.DisplayFor(m => m.Name)</div>
		</div>
		<div class="row">
			<div class="large-2 columns">@Html.LabelFor(m => m.Operations)</div>
			<div class="large-10 columns">@Html.DisplayFor(m => m.Operations)</div>
		</div>
		<div class="row">
			<div class="large-2 columns">@Html.LabelFor(m => m.AssociatedRoleNames)</div>
			<div class="large-10 columns">@Html.DisplayFor(m => m.AssociatedRoleNames)</div>
		</div>
	</div>
</div>

HuskyRescue.Web/Views/AdminIdentityResources/Index.cshtml
@model IEnumerable<HuskyRescue.ViewModel.Admin.ResourceManager.ResourceIndex>
<div class="row">
	<div class="large-6 small-12 small-centered large-centered columns"><h2>System Resources</h2></div>
</div>

<div class="row">
	<div class="large-12 columns">
		<p>
			@Html.ActionLink("Create New", "Create")
		</p>
		<table class="table">
			<tr>
				<th>
					@Html.DisplayNameFor(model => model.Name)
				</th>
				<th>
					@Html.DisplayNameFor(model => model.OperationNames)
				</th>
				<th></th>
			</tr>

			@foreach (var item in Model)
			{
				<tr>
					<td>
						@Html.DisplayFor(modelItem => item.Name)
					</td>
					<td>
						@Html.DisplayFor(modelItem => item.OperationNames)
					</td>
					<td>
						@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
						@Html.ActionLink("Details", "Details", new { id = item.Id }) |
						@Html.ActionLink("Delete", "Delete", new { id = item.Id })
					</td>
				</tr>
			}

		</table>
	</div>
</div>